export type Segment = {
  id: string
  name: string
  cases: number
  aiMaturity: number
  revenueBand: string
  difficulty: 1 | 2 | 3 | 4 | 5
  workers: string[]
  workflow: string[]
  monetization: string
  keyBlocker: string
}

export type BusinessCategory = {
  id: string
  name: string
  description: string
  cases: number
  aiMaturity: number
  adoptionSpace: number
  ordinaryFit: number
  segments: Segment[]
}

export type QuestionOption = {
  id: string
  label: string
  scores: {
    business?: number
    ai?: number
    workflow?: number
    growth?: number
    retention?: number
  }
  hours?: number
  pain?: 'content' | 'sales' | 'delivery' | 'ops' | 'research' | 'automation'
  mode?: string
}

export type Question = {
  id: string
  title: string
  subtitle: string
  options: QuestionOption[]
}

export const categories: BusinessCategory[] = [
  {
    id: 'employee',
    name: '职场打工人',
    description: '白领、行政、销售、运营、产品、程序员和中层管理者，正在面对“会用 AI 的同事”带来的效率差。',
    cases: 12,
    aiMaturity: 58,
    adoptionSpace: 86,
    ordinaryFit: 96,
    segments: [
      {
        id: 'office-worker',
        name: '行政白领',
        cases: 4,
        aiMaturity: 54,
        revenueBand: '工资型收入',
        difficulty: 2,
        workers: ['AI文档助理', 'AI会议纪要员', 'AI流程整理员'],
        workflow: ['会议记录', '周报生成', '资料整理', '流程文档化'],
        monetization: '保住岗位价值、提升晋升筹码、转向复合型岗位',
        keyBlocker: '最危险的不是岗位消失，而是同岗位里会用 AI 的人先被看见。',
      },
      {
        id: 'sales-support',
        name: '销售客服',
        cases: 3,
        aiMaturity: 68,
        revenueBand: '底薪+提成',
        difficulty: 3,
        workers: ['AI客户画像员', 'AI话术教练', 'AI跟进提醒员'],
        workflow: ['客户分层', '异议处理', '跟进话术', '成交复盘'],
        monetization: '提高转化率、缩短跟进周期、积累可迁移销售资产',
        keyBlocker: '重复回复会越来越便宜，客户判断和成交策略才更值钱。',
      },
      {
        id: 'product-tech-worker',
        name: '产品运营',
        cases: 3,
        aiMaturity: 72,
        revenueBand: '工资+项目机会',
        difficulty: 4,
        workers: ['AI需求分析师', 'AI代码助理', 'AI数据复盘官'],
        workflow: ['需求拆解', '原型草稿', '代码辅助', '数据归因'],
        monetization: '从执行者升级为项目负责人或独立产品操盘者',
        keyBlocker: 'AI 会放大强工程师，也会压缩只会搬需求和写重复代码的人。',
      },
      {
        id: 'middle-manager',
        name: '中层管理者',
        cases: 2,
        aiMaturity: 47,
        revenueBand: '管理岗收入',
        difficulty: 4,
        workers: ['AI经营分析师', 'AI任务调度员', 'AI汇报助手'],
        workflow: ['目标拆解', '团队日报', '经营复盘', '上级汇报'],
        monetization: '提高管理半径、减少低效会议、建立个人管理方法论',
        keyBlocker: '不会用 AI 管信息和流程的管理者，会被更小更快的团队挑战。',
      },
    ],
  },
  {
    id: 'boss',
    name: '小微企业老板',
    description: '门店老板、工作室负责人、小团队老板和传统生意经营者，最需要用 AI 降低人力和管理摩擦。',
    cases: 9,
    aiMaturity: 52,
    adoptionSpace: 90,
    ordinaryFit: 88,
    segments: [
      {
        id: 'store-owner',
        name: '门店老板',
        cases: 3,
        aiMaturity: 45,
        revenueBand: '门店现金流',
        difficulty: 3,
        workers: ['AI点评运营员', 'AI活动策划员', 'AI客户回访员'],
        workflow: ['客户评价整理', '活动文案', '老客回访', '朋友圈素材'],
        monetization: '提高到店率、复购率和老客转介绍',
        keyBlocker: '门店不是不需要 AI，而是大量获客和复购动作还在靠老板临时想。',
      },
      {
        id: 'small-team-owner',
        name: '小团队老板',
        cases: 3,
        aiMaturity: 55,
        revenueBand: '项目/服务收入',
        difficulty: 4,
        workers: ['AI项目助理', 'AI招聘筛选员', 'AI财务复盘员'],
        workflow: ['项目排期', '交付检查', '成本复盘', '岗位说明书'],
        monetization: '减少管理损耗，让团队从人盯人变成流程盯结果',
        keyBlocker: '团队越小，越不能把老板时间浪费在重复协调上。',
      },
      {
        id: 'traditional-business',
        name: '传统老板',
        cases: 3,
        aiMaturity: 56,
        revenueBand: '经营型收入',
        difficulty: 4,
        workers: ['AI报价助理', 'AI客户资料员', 'AI方案编辑'],
        workflow: ['客户需求整理', '报价方案', '合同要点', '交付复盘'],
        monetization: '用 AI 把经验变成标准化报价、方案和交付体系',
        keyBlocker: '经验如果只在老板脑子里，就很难复制，也很难抗风险。',
      },
    ],
  },
  {
    id: 'professional',
    name: '专业服务从业者',
    description: '会计、律师、教师、医生、咨询师、培训师等专业人群，正在经历知识劳动的重新定价。',
    cases: 8,
    aiMaturity: 64,
    adoptionSpace: 78,
    ordinaryFit: 72,
    segments: [
      {
        id: 'finance-legal',
        name: '财税法务',
        cases: 3,
        aiMaturity: 66,
        revenueBand: '工资/服务费',
        difficulty: 4,
        workers: ['AI法规检索员', 'AI底稿整理员', 'AI风险提示员'],
        workflow: ['资料检索', '底稿整理', '条款比对', '风险清单'],
        monetization: '从资料处理升级为风险判断和方案解释',
        keyBlocker: '基础资料处理会被压价，专业判断和责任承担更重要。',
      },
      {
        id: 'teacher-coach',
        name: '教培老师',
        cases: 3,
        aiMaturity: 61,
        revenueBand: '工资/课酬/咨询费',
        difficulty: 3,
        workers: ['AI备课助理', 'AI作业点评员', 'AI学员画像师'],
        workflow: ['课程设计', '个性化练习', '作业反馈', '学习路径建议'],
        monetization: '从单次授课升级为个人化学习服务',
        keyBlocker: '只讲标准内容会越来越难，个性化辅导能力会变贵。',
      },
      {
        id: 'consultant-expert',
        name: '行业顾问',
        cases: 2,
        aiMaturity: 68,
        revenueBand: '咨询/顾问费',
        difficulty: 4,
        workers: ['AI行业研究员', 'AI报告编辑', 'AI方案推演员'],
        workflow: ['行业扫描', '访谈整理', '方案生成', '客户汇报'],
        monetization: '把多年经验产品化、报告化、陪跑化',
        keyBlocker: '专家的危险不是 AI 比你更懂，而是别人用 AI 把交付速度拉快十倍。',
      },
    ],
  },
  {
    id: 'transition',
    name: '普通人转型者',
    description: '学生、宝妈、35+转型者、副业探索者，还没有稳定业务，但已经被 AI 时代的能力差距推着往前走。',
    cases: 7,
    aiMaturity: 41,
    adoptionSpace: 82,
    ordinaryFit: 92,
    segments: [
      {
        id: 'student',
        name: '应届生',
        cases: 2,
        aiMaturity: 48,
        revenueBand: '未稳定收入',
        difficulty: 2,
        workers: ['AI学习教练', 'AI简历优化员', 'AI作品集助理'],
        workflow: ['技能学习', '简历优化', '作品集制作', '面试模拟'],
        monetization: '用作品集和项目经验替代空泛证书',
        keyBlocker: '未来简历拼的不是会不会用 AI，而是你用 AI 做出了什么。',
      },
      {
        id: 'side-hustle',
        name: '副业起步',
        cases: 3,
        aiMaturity: 39,
        revenueBand: '0-1万/月',
        difficulty: 3,
        workers: ['AI选题员', 'AI产品验证员', 'AI执行助理'],
        workflow: ['方向筛选', '低成本验证', '内容发布', '用户反馈'],
        monetization: '资料包、模板、服务、咨询、小产品',
        keyBlocker: '普通人最容易死在方向太多、执行太散、没有持续反馈。',
      },
      {
        id: 'career-change',
        name: '35+转型',
        cases: 2,
        aiMaturity: 36,
        revenueBand: '不稳定/转型期',
        difficulty: 4,
        workers: ['AI经验盘点师', 'AI行业研究员', 'AI转型路线顾问'],
        workflow: ['经验盘点', '市场机会扫描', '能力补差', '转型作品输出'],
        monetization: '把过往经验包装成咨询、培训、服务或内容资产',
        keyBlocker: '年龄不是最大问题，最大问题是经验没有产品化，能力没有被看见。',
      },
    ],
  },
  {
    id: 'content',
    name: '内容型一人公司',
    description: '靠短视频、图文、直播、栏目化内容持续获客，AI 主要接管选题、脚本、标题、拆条和复盘。',
    cases: 11,
    aiMaturity: 73,
    adoptionSpace: 82,
    ordinaryFit: 86,
    segments: [
      {
        id: 'video-daily',
        name: '短视频IP',
        cases: 4,
        aiMaturity: 78,
        revenueBand: '1万-5万/月',
        difficulty: 3,
        workers: ['AI选题研究员', 'AI脚本助理', 'AI数据复盘官'],
        workflow: ['早间热点扫描', '生成3条脚本初稿', '人工定稿拍摄', '晚间数据复盘'],
        monetization: '广告分成、私域引流、课程和咨询',
        keyBlocker: '能日更，但不会用数据反向训练选题。',
      },
      {
        id: 'newsletter',
        name: '公众号作者',
        cases: 3,
        aiMaturity: 66,
        revenueBand: '5千-3万/月',
        difficulty: 3,
        workers: ['AI资料员', 'AI结构编辑', 'AI标题实验员'],
        workflow: ['资料抓取', '观点提纲', '长文初稿', '标题A/B版本'],
        monetization: '流量主、社群、付费专栏',
        keyBlocker: 'AI能写，但人设和观点密度不稳定。',
      },
      {
        id: 'xiaohongshu',
        name: '小红书博主',
        cases: 2,
        aiMaturity: 72,
        revenueBand: '5千-2万/月',
        difficulty: 4,
        workers: ['AI选题雷达', 'AI笔记编辑', 'AI评论分析师'],
        workflow: ['爆款拆解', '笔记模板化', '批量封面文案', '评论需求归类'],
        monetization: '商单、引流、资料包',
        keyBlocker: '平台反馈快，但账号定位容易分散。',
      },
      {
        id: 'bilibili',
        name: 'B站UP主',
        cases: 2,
        aiMaturity: 69,
        revenueBand: '1万-4万/月',
        difficulty: 4,
        workers: ['AI课程研究员', 'AI分镜助理', 'AI切片助理'],
        workflow: ['专题研究', '分镜脚本', '长视频录制', '切片二次分发'],
        monetization: '充电、课程、咨询、品牌合作',
        keyBlocker: '内容质量高，但制作周期容易失控。',
      },
    ],
  },
  {
    id: 'knowledge',
    name: '课程/知识付费一人公司',
    description: '把经验产品化，靠课程、训练营、社群和模板交付变现，AI 主要接管销售、助教、作业点评和复盘。',
    cases: 8,
    aiMaturity: 76,
    adoptionSpace: 88,
    ordinaryFit: 78,
    segments: [
      {
        id: 'online-course',
        name: '课程讲师',
        cases: 3,
        aiMaturity: 82,
        revenueBand: '2万-8万/月',
        difficulty: 3,
        workers: ['AI课程策划师', 'AI销售跟进员', 'AI助教'],
        workflow: ['需求调研', '大纲生成', '私域答疑', '作业点评'],
        monetization: '录播课、训练营、会员订阅',
        keyBlocker: '内容能做出来，但转化和交付链路常常断开。',
      },
      {
        id: 'bootcamp',
        name: '训练营操盘手',
        cases: 3,
        aiMaturity: 74,
        revenueBand: '3万-10万/月',
        difficulty: 4,
        workers: ['AI招生助理', 'AI班主任', 'AI直播复盘官'],
        workflow: ['线索筛选', '开营提醒', '直播总结', '学员分层跟进'],
        monetization: '短训营、进阶营、私教咨询',
        keyBlocker: '流程复杂，最容易死在运营细节。',
      },
      {
        id: 'community',
        name: '付费社群',
        cases: 2,
        aiMaturity: 63,
        revenueBand: '1万-5万/月',
        difficulty: 3,
        workers: ['AI社群运营员', 'AI话题主持人', 'AI资料管理员'],
        workflow: ['每日话题', '精华沉淀', '成员问题归档', '续费提醒'],
        monetization: '年费社群、资料库、线下活动',
        keyBlocker: '活跃靠人撑，续费缺少可感知成果。',
      },
    ],
  },
  {
    id: 'consulting',
    name: '咨询/顾问一人公司',
    description: '靠专业判断和项目交付收费，AI 主要接管调研、诊断报告、方案初稿和客户跟进。',
    cases: 6,
    aiMaturity: 69,
    adoptionSpace: 79,
    ordinaryFit: 62,
    segments: [
      {
        id: 'ai-consultant',
        name: 'AI转型顾问',
        cases: 2,
        aiMaturity: 88,
        revenueBand: '3万-12万/月',
        difficulty: 4,
        workers: ['AI调研员', 'AI方案架构师', 'AI项目助理'],
        workflow: ['客户访谈整理', '流程诊断', '方案初稿', '项目周报'],
        monetization: '咨询费、实施费、长期顾问',
        keyBlocker: '懂工具的人多，懂业务改造的人少。',
      },
      {
        id: 'brand-consultant',
        name: '品牌顾问',
        cases: 2,
        aiMaturity: 57,
        revenueBand: '1万-6万/月',
        difficulty: 3,
        workers: ['AI定位分析师', 'AI内容教练', 'AI案例编辑'],
        workflow: ['用户画像', '定位提案', '内容日历', '案例包装'],
        monetization: '顾问费、陪跑、内容代运营',
        keyBlocker: '个性化强，标准化交付难。',
      },
      {
        id: 'business-model',
        name: '商业顾问',
        cases: 2,
        aiMaturity: 62,
        revenueBand: '2万-8万/月',
        difficulty: 5,
        workers: ['AI行业研究员', 'AI商业分析师', 'AI报告编辑'],
        workflow: ['行业扫描', '竞品拆解', '模型假设', '报告成稿'],
        monetization: '诊断报告、战略陪跑、企业内训',
        keyBlocker: 'AI能出报告，但关键洞察仍靠人。',
      },
    ],
  },
  {
    id: 'ecommerce',
    name: '电商/直播一人公司',
    description: '围绕选品、脚本、客服、投放和复盘构建小团队业务，AI 空间很大但落地难度更高。',
    cases: 6,
    aiMaturity: 49,
    adoptionSpace: 73,
    ordinaryFit: 70,
    segments: [
      {
        id: 'douyin-shop',
        name: '抖音小店',
        cases: 2,
        aiMaturity: 48,
        revenueBand: '5千-5万/月',
        difficulty: 4,
        workers: ['AI选品员', 'AI客服', 'AI投放复盘官'],
        workflow: ['选品池', '商品文案', '客服话术', '投放复盘'],
        monetization: '商品差价、达人分销、自播转化',
        keyBlocker: '供应链和投放变量太多，AI只能先做辅助。',
      },
      {
        id: 'cross-border',
        name: '跨境电商',
        cases: 2,
        aiMaturity: 52,
        revenueBand: '1万-6万/月',
        difficulty: 4,
        workers: ['AI翻译本地化', 'AI客服', 'AI Listing优化师'],
        workflow: ['竞品扫描', 'Listing生成', '多语客服', '评价分析'],
        monetization: '平台店铺、独立站、联盟分销',
        keyBlocker: '平台规则和物流售后仍需要强人工控制。',
      },
      {
        id: 'live-commerce',
        name: '直播带货',
        cases: 2,
        aiMaturity: 39,
        revenueBand: '5千-4万/月',
        difficulty: 5,
        workers: ['AI直播脚本员', 'AI场控助手', 'AI复盘官'],
        workflow: ['直播脚本', '话术卡片', '用户问题整理', '场次复盘'],
        monetization: '佣金、坑位、私域复购',
        keyBlocker: '现场能力和供应链决定上限，AI只能补后台。',
      },
    ],
  },
  {
    id: 'local',
    name: '本地服务一人公司',
    description: '摄影、设计、翻译、探店、门店代运营等本地服务，AI 主要接管报价、样稿、交付文档和客户沟通。',
    cases: 4,
    aiMaturity: 71,
    adoptionSpace: 66,
    ordinaryFit: 74,
    segments: [
      {
        id: 'ai-photo',
        name: 'AI修图',
        cases: 1,
        aiMaturity: 65,
        revenueBand: '5千-3万/月',
        difficulty: 3,
        workers: ['AI修图助理', 'AI报价助理', 'AI客户沟通员'],
        workflow: ['需求确认', '样片生成', '批量修图', '交付说明'],
        monetization: '拍摄套餐、修图包、企业素材服务',
        keyBlocker: '审美和客户预期管理很关键。',
      },
      {
        id: 'ai-design',
        name: 'AI设计师',
        cases: 2,
        aiMaturity: 78,
        revenueBand: '1万-5万/月',
        difficulty: 3,
        workers: ['AI视觉参考员', 'AI提案助理', 'AI交付检查员'],
        workflow: ['风格板', '提案初稿', '多版本迭代', '交付清单'],
        monetization: 'Logo、物料、店铺视觉、品牌包',
        keyBlocker: '出图快，但商业审美和需求判断不能丢。',
      },
      {
        id: 'translation',
        name: 'AI翻译',
        cases: 1,
        aiMaturity: 86,
        revenueBand: '5千-2万/月',
        difficulty: 2,
        workers: ['AI术语管理员', 'AI初译员', 'AI审校助理'],
        workflow: ['术语表', '机器初译', '人工审校', '风格统一'],
        monetization: '文档翻译、本地化顾问、长期外包',
        keyBlocker: '低端翻译会被压价，高端审校仍有机会。',
      },
    ],
  },
  {
    id: 'tools',
    name: '工具/SaaS一人公司',
    description: '独立开发者、插件、自动化工具和 GPT 应用，AI 可以大幅压缩开发、客服和文档成本。',
    cases: 5,
    aiMaturity: 91,
    adoptionSpace: 83,
    ordinaryFit: 42,
    segments: [
      {
        id: 'chrome-plugin',
        name: '插件开发者',
        cases: 2,
        aiMaturity: 92,
        revenueBand: '5千-5万/月',
        difficulty: 4,
        workers: ['AI产品经理', 'AI代码助理', 'AI客服文档员'],
        workflow: ['需求池', '代码生成', '测试修复', '帮助文档'],
        monetization: '订阅、一次性买断、企业授权',
        keyBlocker: '开发速度很快，但分发和留存更难。',
      },
      {
        id: 'gpt-app',
        name: 'GPT开发者',
        cases: 1,
        aiMaturity: 88,
        revenueBand: '5千-3万/月',
        difficulty: 3,
        workers: ['AI原型设计师', 'AI提示词工程师', 'AI增长助理'],
        workflow: ['场景验证', 'Prompt打磨', 'MVP发布', '用户反馈迭代'],
        monetization: '会员订阅、模板售卖、企业定制',
        keyBlocker: '同质化严重，必须卡住具体场景。',
      },
      {
        id: 'automation-tool',
        name: '自动化开发',
        cases: 2,
        aiMaturity: 95,
        revenueBand: '1万-8万/月',
        difficulty: 5,
        workers: ['AI流程架构师', 'AI代码助理', 'AI运维助手'],
        workflow: ['流程拆解', '自动化脚本', '异常监控', '迭代发布'],
        monetization: '工具订阅、自动化实施、企业顾问',
        keyBlocker: '技术门槛高，但护城河也更深。',
      },
    ],
  },
  {
    id: 'research',
    name: '投资/研究型一人公司',
    description: '靠信息收集、研究框架、组合复盘和观点输出建立优势，AI 接管数据整理和初步分析。',
    cases: 3,
    aiMaturity: 74,
    adoptionSpace: 69,
    ordinaryFit: 38,
    segments: [
      {
        id: 'stock-research',
        name: '股市研究员',
        cases: 1,
        aiMaturity: 68,
        revenueBand: '不稳定',
        difficulty: 5,
        workers: ['AI财报分析师', 'AI新闻监控员', 'AI组合复盘官'],
        workflow: ['公告监控', '财报提取', '观点草稿', '持仓复盘'],
        monetization: '投研订阅、咨询、资产配置服务',
        keyBlocker: '投资结果不能承诺，合规边界要非常清楚。',
      },
      {
        id: 'quant',
        name: '量化交易',
        cases: 1,
        aiMaturity: 82,
        revenueBand: '不稳定',
        difficulty: 5,
        workers: ['AI策略研究员', 'AI回测助理', 'AI风控提醒员'],
        workflow: ['策略假设', '回测', '风险监控', '交易日志'],
        monetization: '自营、策略订阅、技术服务',
        keyBlocker: '模型不等于收益，风险控制比想法重要。',
      },
      {
        id: 'crypto-analyst',
        name: '加密分析',
        cases: 1,
        aiMaturity: 75,
        revenueBand: '不稳定',
        difficulty: 5,
        workers: ['AI链上监控员', 'AI情绪分析师', 'AI日报编辑'],
        workflow: ['链上数据', '消息监控', '日报生成', '风险提示'],
        monetization: '订阅、社群、工具分销',
        keyBlocker: '波动极大，内容合规和风险提示必须前置。',
      },
    ],
  },
  {
    id: 'freelance',
    name: '自由职业/接单型一人公司',
    description: '从接单升级为标准化服务，AI 主要接管提案、报价、交付检查和客户复盘。',
    cases: 7,
    aiMaturity: 77,
    adoptionSpace: 76,
    ordinaryFit: 84,
    segments: [
      {
        id: 'indie-dev',
        name: '独立开发者',
        cases: 3,
        aiMaturity: 85,
        revenueBand: '1万-8万/月',
        difficulty: 4,
        workers: ['AI需求分析师', 'AI代码助理', 'AI测试员'],
        workflow: ['需求澄清', '功能拆解', '代码生成', '测试修复'],
        monetization: '项目制、维护费、模板工具',
        keyBlocker: '能做项目，但产品化和获客常常缺失。',
      },
      {
        id: 'copywriter',
        name: '文案策划',
        cases: 2,
        aiMaturity: 72,
        revenueBand: '5千-3万/月',
        difficulty: 2,
        workers: ['AI资料员', 'AI标题师', 'AI初稿员'],
        workflow: ['客户访谈', '竞品拆解', '文案初稿', '版本迭代'],
        monetization: '文案项目、品牌月服、内容顾问',
        keyBlocker: 'AI拉低基础文案价格，必须升级为策略服务。',
      },
      {
        id: 'data-analyst',
        name: '数据分析',
        cases: 2,
        aiMaturity: 78,
        revenueBand: '1万-5万/月',
        difficulty: 3,
        workers: ['AI数据清洗员', 'AI图表分析师', 'AI报告编辑'],
        workflow: ['数据清洗', '图表生成', '异常解释', '报告输出'],
        monetization: '分析报告、看板搭建、长期数据顾问',
        keyBlocker: '报表会越来越便宜，业务解释才值钱。',
      },
    ],
  },
]

export const questions: Question[] = [
  {
    id: 'income_mode',
    title: '你现在最接近哪种状态？',
    subtitle: '选最接近你当前状态的一项。',
    options: [
      { id: 'employee', label: '职场打工人：白领、销售、运营、产品、程序员', mode: 'employee', scores: { business: 8, growth: 5 } },
      { id: 'boss', label: '小微老板：门店、工作室、小团队、传统生意', mode: 'boss', scores: { business: 14, retention: 7 } },
      { id: 'professional', label: '专业服务：会计、律师、教师、医生、顾问', mode: 'professional', scores: { business: 12, retention: 8 } },
      { id: 'content', label: '内容创作者：视频、文章、直播、账号', mode: 'content', scores: { business: 10, growth: 8 } },
      { id: 'freelance', label: '自由职业/接单：设计、开发、翻译、策划', mode: 'freelance', scores: { business: 10, workflow: 5 } },
      { id: 'transition', label: '转型探索者：学生、副业、宝妈、35+转型', mode: 'transition', scores: { business: 2, growth: 2 } },
    ],
  },
  {
    id: 'product',
    title: '你有没有能持续变现或被认可的核心价值？',
    subtitle: '可以是产品、技能、服务、项目经验，也可以是你在岗位里的不可替代能力。',
    options: [
      { id: 'none', label: '还不清楚，主要靠平台、公司、甲方或运气', scores: { business: 2, retention: 1 } },
      { id: 'rough', label: '有一些能力或产品雏形，但还不稳定', scores: { business: 9, retention: 4 } },
      { id: 'mature', label: '有明确价值，能持续带来收入、机会或认可', scores: { business: 18, retention: 12 } },
    ],
  },
  {
    id: 'time_sink',
    title: '你每天最耗时间的是什么？',
    subtitle: '这里决定你最应该补上的第一个 AI 员工是谁。',
    options: [
      { id: 'content', label: '内容创作：写文案、拍视频、做设计', pain: 'content', scores: { ai: 4, workflow: 3 } },
      { id: 'sales', label: '销售跟进：私信、评论、客户沟通', pain: 'sales', scores: { growth: 4, workflow: 2 } },
      { id: 'delivery', label: '交付服务：上课、咨询、售后、作业点评', pain: 'delivery', scores: { retention: 4, workflow: 3 } },
      { id: 'ops', label: '运营维护：发圈、更新、排期、数据分析', pain: 'ops', scores: { workflow: 4, ai: 2 } },
      { id: 'research', label: '学习研究：找资料、看趋势、做判断', pain: 'research', scores: { ai: 3, business: 2 } },
    ],
  },
  {
    id: 'ai_usage',
    title: '你现在怎么用 AI？',
    subtitle: '不要看你会不会聊天，要看 AI 有没有进入你的固定流程。',
    options: [
      { id: 'none', label: '几乎不用，或者不知道从哪开始', scores: { ai: 0, workflow: 0 } },
      { id: 'casual', label: '偶尔让 AI 帮我写点东西', scores: { ai: 7, workflow: 2 } },
      { id: 'frequent', label: '经常用 AI，但还没有固定流程', scores: { ai: 15, workflow: 6 } },
      { id: 'system', label: '有固定流程，AI 每天都在干活', scores: { ai: 24, workflow: 14 } },
    ],
  },
  {
    id: 'sop',
    title: '你有没有固定 SOP？',
    subtitle: '没有 SOP，就没有真正的 AI 员工，只有临时问答。',
    options: [
      { id: 'none', label: '没有，每次都临时发挥', scores: { workflow: 0 } },
      { id: 'partial', label: '有一些，但不完整，靠经验补', scores: { workflow: 8 } },
      { id: 'complete', label: '有完整 SOP，并且能交给别人执行', scores: { workflow: 18 } },
    ],
  },
  {
    id: 'private_pool',
    title: '你有没有私域或客户池？',
    subtitle: '可以是客户、粉丝、同事资源、行业人脉，也可以是持续能触达的人群。',
    options: [
      { id: 'none', label: '没有，每次都重新找客户', scores: { growth: 0, retention: 0 } },
      { id: 'small', label: '有，但不到 1000 人', scores: { growth: 5, retention: 3 } },
      { id: 'mid', label: '有 1000-5000 人，可以持续触达', scores: { growth: 11, retention: 6 } },
      { id: 'large', label: '有 5000 人以上，有稳定转化机会', scores: { growth: 18, retention: 9 } },
    ],
  },
  {
    id: 'acquisition',
    title: '你有没有持续获客渠道？',
    subtitle: '不是偶尔爆一次，而是每月都能新增线索。',
    options: [
      { id: 'none', label: '没有，基本靠碰运气', scores: { growth: 0 } },
      { id: 'unstable', label: '有，但不稳定，时好时坏', scores: { growth: 7 } },
      { id: 'stable', label: '有稳定渠道，每月都有新增客户', scores: { growth: 18 } },
    ],
  },
  {
    id: 'retention',
    title: '你有没有复购或长期交付？',
    subtitle: '一次性成交只能活着，复购和订阅才能变成系统。',
    options: [
      { id: 'none', label: '没有，基本是一锤子买卖', scores: { retention: 0 } },
      { id: 'some', label: '有少量复购，但不稳定', scores: { retention: 8 } },
      { id: 'stable', label: '有稳定复购、订阅或长期服务', scores: { retention: 18 } },
    ],
  },
  {
    id: 'repeat_hours',
    title: '你每周有多少小时被重复劳动吃掉？',
    subtitle: '重复劳动越多，说明你的 AI 员工越应该立刻上岗。',
    options: [
      { id: 'unknown', label: '不知道，没认真算过', hours: 10, scores: { workflow: 1 } },
      { id: 'low', label: '10 小时以下', hours: 6, scores: { workflow: 4 } },
      { id: 'mid', label: '10-20 小时', hours: 15, scores: { workflow: 6 } },
      { id: 'high', label: '20 小时以上', hours: 24, scores: { workflow: 5 } },
    ],
  },
  {
    id: 'ai_wish',
    title: '你最想让 AI 替你干什么？',
    subtitle: '这会影响报告里的第一优先级建议。',
    options: [
      { id: 'content', label: '写文案、做内容、出脚本', pain: 'content', scores: { ai: 3 } },
      { id: 'sales', label: '回复客户、销售跟进、处理异议', pain: 'sales', scores: { growth: 3 } },
      { id: 'data', label: '数据分析、直播复盘、经营判断', pain: 'ops', scores: { workflow: 3 } },
      { id: 'research', label: '学习研究、信息收集、趋势扫描', pain: 'research', scores: { ai: 3 } },
      { id: 'automation', label: '全自动运营，少让我亲自盯着', pain: 'automation', scores: { workflow: 4 } },
    ],
  },
]

export const workerProfiles = {
  content: {
    name: 'AI内容增长员',
    reason: '你的最大时间黑洞在选题、脚本、标题和内容改稿。先训练它，最容易立刻看到产出。',
    capabilities: ['每天生成选题池', '拆解爆款结构', '输出脚本和标题版本', '根据数据给出改稿建议'],
    firstSteps: ['整理最近30条内容数据', '沉淀你的选题标准', '建立标题和脚本模板', '每天固定让 AI 输出 3 个版本'],
  },
  sales: {
    name: 'AI销售跟进员',
    reason: '客户咨询和跟进高度重复，而且直接影响成交。它是最容易释放老板时间的 AI 员工。',
    capabilities: ['自动回答常见问题', '筛选高意向客户', '生成跟进话术', '每天输出销售日报'],
    firstSteps: ['整理100条常见咨询', '写清楚成交判断标准', '沉淀你的异议处理话术', '先做人工审核版自动回复'],
  },
  delivery: {
    name: 'AI交付助教',
    reason: '你的交付依赖本人经验，规模一大就会累死。AI 助教先接管答疑、作业点评和复盘初稿。',
    capabilities: ['生成课后总结', '点评作业初稿', '整理高频问题', '提醒学员完成关键动作'],
    firstSteps: ['整理课程大纲和作业标准', '收集优秀/普通作业样本', '制作点评规则', '每次交付后让 AI 出复盘'],
  },
  ops: {
    name: 'AI运营复盘官',
    reason: '你不是缺执行，而是缺每天稳定复盘的系统。这个员工负责把数据变成下一步动作。',
    capabilities: ['汇总运营数据', '发现异常波动', '生成复盘报告', '拆出明日行动清单'],
    firstSteps: ['确定每天要看的 5 个指标', '建立数据记录表', '固定复盘模板', '每天结束后生成经营日报'],
  },
  research: {
    name: 'AI选题研究员',
    reason: '你花大量时间找资料和判断趋势，这类工作最适合先交给 AI 做初筛。',
    capabilities: ['监控热点趋势', '整理行业资料', '生成观点提纲', '输出可发布选题'],
    firstSteps: ['列出你的 20 个核心关键词', '确定信息源清单', '建立早报模板', '每天早上让 AI 推送 5 个机会'],
  },
  automation: {
    name: 'AI运营调度员',
    reason: '你已经意识到问题不在单点工具，而在流程没有串起来。先训练调度员，统一管理任务和节奏。',
    capabilities: ['拆解每日任务', '调用不同 AI 员工', '跟踪执行状态', '生成老板检查清单'],
    firstSteps: ['列出一周内重复任务', '定义每个任务的输入输出', '建立日计划模板', '从一条流程开始自动化'],
  },
} as const
